Incomplete language files shouldn't make errors
Ghoulboy78/World-edit-scarpet pull request #26
Opened 2020-12-26 12:16 UTC by Ghoulboy78

Fixes #22
Basically, before this, any non-empty language file would be treated as complete, and just be accepted, without any checks for completeness. This is obviously a problem, so instead I added it so in case there is no translation for a particular item, it will default to `en_us`.
I do have to figure out how to tell the player that the translation is incomplete, maybe by printing to logger? idk rly.

2020-12-26 15:51 UTC, Firigion commented
Incomplete translation should probably be informed to the player when changing languages and when loading the app in a different language.

2020-12-26 16:23 UTC, Ghoulboy78 commented on world-edit.sc
> +    ['lang', _()->(print(format(_translate('help_app_lang')+' '+global_lang))), false],
true

2020-12-26 16:24 UTC, Ghoulboy78 commented on world-edit.sc
> +    ['lang', _()->(print(format(_translate('help_app_lang')+' '+global_lang))), false],
omfg how could I forget I even speak a language like that...

2020-12-26 16:28 UTC, Ghoulboy78 commented on world-edit.sc
> +    ['lang', _()->(print(format(_translate('help_app_lang')+' '+global_lang))), false],
wait tho i have no clu how to do that. @altrisi ?

2020-12-26 16:29 UTC, Ghoulboy78 commented on world-edit.sc
> +    ['lang', _()->(print(format(_translate('help_app_lang')+' '+global_lang))), false],
nvm ill do old style

2020-12-26 16:37 UTC, Ghoulboy78 commented
@gnembon can scarpet support reading jsons? cos that would be very useful for the lang files, similar to mc.

2020-12-26 21:05 UTC, BisUmTo approved these changes

2020-12-27 01:35 UTC, Firigion approved these changes

2020-12-27 01:51 UTC, altrisi commented
> 
> 
> can scarpet support reading jsons? cos that would be very useful for the lang files, similar to mc.

Well, currently it can't, but since the next version it may be able to. Check gnembon/fabric-carpet#643

2020-12-27 01:53 UTC, altrisi commented on world-edit.sc
> +    ['lang', _()->(print(format(_translate('help_app_lang')+' '+global_lang))), false],
`_translate('msg', global_lang)`
...
`msg = Selected language: %s`

Or, since you are directly format-printing, you can use `_print(player, 'msg', global_lang)`

2020-12-27 01:58 UTC, altrisi commented on world-edit.sc
> +_translate(key, replace_list) -> (
You did something wrong here.

In a PR, `_translate(key, replace_list)` was changed to `_translate(key, ... replace_list)`, and the first functionality went into `_translate_internal(key, replace_list)`. With this change, multiple things stop working properly (try /world-edit).

2020-12-27 01:59 UTC, altrisi commented on world-edit.sc
> +_translate(key, replace_list) -> (
This may have been introduced in b10b2d79ae9f1b8f7991d31f4627d6d3ec494a93

2020-12-27 02:04 UTC, altrisi commented on world-edit.sc
> +_translate(key, replace_list) -> (
It actually comes from before, in #19, where you replaced `_print(...)` with the old one (when merging).

`_print` and `_error` should call `_translate_internal` instead, which was also deleted there.

2020-12-27 02:08 UTC, altrisi commented on world-edit.sc
> +_translate(key, replace_list) -> (
(Github doesn't let me make those click-to-solve buttons here for some reason)
Basically it would be changing this:
```py
_translate(key, replace_list) -> (
    lang_id = global_lang;
    if(lang_id == null || !has(global_langs, lang_id),
        lang_id = global_lang_ids:0);
    if(key == null,
        null,
        str(global_langs:lang_id:key, replace_list)
    )
);
_print(player, key, ... replace) ->
    print(player, format(_translate(key, replace)));
_error(player, key, ... replace)->
    exit(print(player, format(_translate(key, replace))));
```
to this:
```py
_translate(key, ... replace_list) -> 
    _translate_internal(key, replace_list);
_translate_internal(key, replace_list) -> (
    lang_id = global_lang;
    if(lang_id == null || !has(global_langs, lang_id),
        lang_id = global_lang_ids:0);
    if(key == null,
        null,
        str(global_langs:lang_id:key, replace_list)
    )
);
_print(player, key, ... replace) ->
    print(player, format(_translate_internal(key, replace)));
_error(player, key, ... replace)->
    exit(print(player, format(_translate_internal(key, replace))));
```

2020-12-27 02:08 UTC, altrisi commented on world-edit.sc
> +_translate(key, replace_list) -> (
The change was done to allow simple usage of `_translate()` with variable or no arguments, without having to pass a list or empty list.

2020-12-27 02:10 UTC, altrisi requested changes
Comment above.

_Edit: This was not expected_

2020-12-27 08:42 UTC, Ghoulboy78 commented on world-edit.sc
> +_translate(key, replace_list) -> (
but I tested and that can be done without `_translate_internall()` func. also I added the vararg back to `_translate()`, just havent committed yet cos im fixing bugs

2020-12-27 08:45 UTC, Ghoulboy78 commented
> > can scarpet support reading jsons? cos that would be very useful for the lang files, similar to mc.
> 
> Well, currently it can't, but since the next version it may be able to. Check [gnembon/fabric-carpet#643](https://github.com/gnembon/fabric-carpet/pull/643)

looks impressive!

2020-12-27 08:45 UTC, Ghoulboy78 commented
Looking forward to it

2020-12-27 08:47 UTC, Ghoulboy78 commented on world-edit.sc
> +_translate(key, replace_list) -> (
ah wait no I get the point now.

2020-12-27 08:50 UTC, Ghoulboy78 commented on world-edit.sc
> +_translate(key, replace_list) -> (
done

2020-12-27 08:50 UTC, merged