Translations v2
Ghoulboy78/World-edit-scarpet pull request #31
Opened 2021-01-05 00:51 UTC by altrisi

This PR overhauls the way translations work in the app in order to not be hardcoded to specific languages but load dinamically.

**NOTE**: This PR _requires_ changes from latest Carpet commits (JSON handling), but doesn't currently work with the latest (some other functionality of the app also doesn't work properly, caused by gnembon/fabric-carpet#657). In order to test it, well, I'll provide a way in a moment.

As a summary, this PR:
- Changes translations to be stored in JSON instead of Java Properties
- Removes hardcoded list of languages to be dynamically generated from the list of available language files
- (Re?)Adds a page with a list of languages when running `/world-edit lang` without arguments
- Regenerates the `en_us` language file on startup to be usable as a template to create other languages (async, cause why not)
- Sadly messes up the spaces in the `it_it` language file (it was a lot worse, but I was tired after reordering all language keys)
- Fixes the `%` symbol being required to be passed as a param: To escape it in Java, you need to use `%%`

The app will log whenever a translation string that is going to be used is not found instead of when loading language (cheaper to load).

New/touched untranslated lang strings:
- All inside `langs_*`

2021-01-05 17:24 UTC, Ghoulboy78 requested changes

2021-01-05 17:24 UTC, Ghoulboy78 commented on world-edit.sc
> -            for(global_missing_translations:lang,logger('warn','[World-Edit scarpet]     '+_+', current en_us translation: '+global_langs:global_lang:_))
I did want to keep that, in case there are many missing translations, so the players don't need to be bombarded, only server admin

2021-01-05 17:24 UTC, Ghoulboy78 commented on world-edit.sc
> +            _print(player(),'langs_completeness',_translate('language'),round(100 - missing/length(global_lang_keys)*100),missing)
I wanted to add the exact missing translations, cos its gonna be impossible to do it later if not.

2021-01-05 17:25 UTC, Ghoulboy78 commented on world-edit.sc
> +            _print(player(),'langs_completeness',_translate('language'),round(100 - missing/length(global_lang_keys)*100),missing)
like the server admin will have hell trying to figure out which ones are missing and which are present.

2021-01-05 17:44 UTC, Ghoulboy78 commented
Look, I know you don't like prolonging prs, but imma wait on this one. If you want, you keep on working on this one without updating from master, and Ill fix conflicts right when merging. This is cos im super busy personally, also cos I dont like having to depend on unreleased versions of fabric-carpet, especially as the split() bug is still in there as of now, and idk when its gonna be fixed. Ill mark this as a draft till then.

2021-01-05 18:02 UTC, altrisi commented on world-edit.sc
> +            _print(player(),'langs_completeness',_translate('language'),round(100 - missing/length(global_lang_keys)*100),missing)
Now that I'm thinking, that could actually be done async, in a task, so it doesn't block main thread even with a lot of keys.

2021-01-05 18:02 UTC, altrisi commented
Don't worry, it makes sense.

2021-01-05 19:38 UTC, Ghoulboy78 commented on world-edit.sc
> +            _print(player(),'langs_completeness',_translate('language'),round(100 - missing/length(global_lang_keys)*100),missing)
Very fair point... idrk much abt async and stuff like that...

2021-01-05 21:25 UTC, altrisi commented on world-edit.sc
> -            for(global_missing_translations:lang,logger('warn','[World-Edit scarpet]     '+_+', current en_us translation: '+global_langs:global_lang:_))
Actually the players weren't sent anything except at the beginning, which was already there.

Fixed anyway

2021-01-05 21:26 UTC, altrisi commented on world-edit.sc
> +            _print(player(),'langs_completeness',_translate('language'),round(100 - missing/length(global_lang_keys)*100),missing)
Readded as an async task. It's only about 2x performance, but considering it'll get better the more translations there are, I think it's worth.

2021-01-07 16:25 UTC, Ghoulboy78 approved these changes

2021-01-08 16:41 UTC, Firigion approved these changes

2021-01-09 08:35 UTC, Ghoulboy78 commented
Ill merge when next release of fc comes out which adds the json stuff.

2021-01-09 17:04 UTC, Firigion commented
Would you mind editing collaborate.md to describe how to add a translation and properly use the `_print()` command?

2021-01-09 17:30 UTC, altrisi commented
Added.

2021-01-09 17:47 UTC, Ghoulboy78 commented on CONTRIBUTING.md
> +If you want to print a message as an output to the player, the easiest way is using the `_print(player, message_id, ...extra_args))`
U added an extra semicolon at the end of `_print(player, message_id, extra_args)`

2021-01-09 17:49 UTC, Ghoulboy78 commented on CONTRIBUTING.md
> -telling the user what's wrong.
You took out the `_error ` function documentation?

2021-01-09 22:49 UTC, altrisi commented on CONTRIBUTING.md
> -telling the user what's wrong.
No, I moved it right below with the auxiliary translating functions.

2021-01-09 22:49 UTC, altrisi commented on CONTRIBUTING.md
> +If you want to print a message as an output to the player, the easiest way is using the `_print(player, message_id, ...extra_args))`
Oops

2021-01-10 07:44 UTC, Ghoulboy78 commented on CONTRIBUTING.md
> -telling the user what's wrong.
ah ok didnt notice oops

2021-01-10 07:46 UTC, Ghoulboy78 commented on CONTRIBUTING.md
> +so you have full freedom to what you use if for
so you have full freedom to what you use _if_ for

2021-01-10 07:47 UTC, Ghoulboy78 commented on CONTRIBUTING.md
> +it will use the default english values for those.
I think you should maybe specify US english? Cos if not then people might expect grammar etc. to be accurate...

2021-01-14 02:49 UTC, BisUmTo approved these changes

2021-01-23 21:07 UTC, altrisi commented
Note: This has 3 approvals since over 10 days ago. Can I/someone click the rebase and merge button?

I'll carefully fix conflicts in other PRs after that.

2021-01-23 22:42 UTC, Firigion commented
Yes plz. I just didn't dare do it myself.

2021-01-24 07:53 UTC, Ghoulboy78 commented
ye It's good to be merged now.

2021-01-24 09:50 UTC, merged