Brush overhaul
Ghoulboy78/World-edit-scarpet pull request #49
Opened 2021-02-01 07:04 UTC by Ghoulboy78

Adding way to easily add new brushes.

2021-02-01 15:22 UTC, BisUmTo commented on world-edit.data/langs/it_it.json
>    "entry_undo_2": "w     posizioni affettati: %s",
"entry_undo_2": "w     posizioni affette: %s",

2021-02-01 15:27 UTC, Ghoulboy78 commented on world-edit.data/langs/it_it.json
>    "entry_undo_2": "w     posizioni affettati: %s",
ah certo non stiamo tagliando a pezzi...

2021-02-01 18:19 UTC, Ghoulboy78 commented
> That being said, I don't expect someone _wanting_ to undo something in the dimension they are not in. I still think having undo histories per dimension is a better idea, but idk what other people think...

Not too hard to do. Guys, can we have a vote? 👍 if you want to have separate undo hsitories for each dim, 👎 if you just want to have it like it is rn, so 1 undo history for all dims

2021-02-01 22:39 UTC, Firigion requested changes
Good work! You really need to be more careful when modifying existing code, tho. Especially if it was written by someone else. This is the third or fourth time you accidentally delete features that had been implemented by someone else.

Also, why you are overhauling brush, would you mind importing `pyramid` over form carpet's draw app/comand? That was a shape I was missing.

2021-02-01 22:39 UTC, Firigion commented on world-edit.sc
> +            add_to_history('action_ellipsoid',player())
You removed hollow support for these shapes. Cube and cuboid were reworked in #45, and then later mistakenly removed when merging the PR, so those will be back in a later PR of mine, don't bother about those. Do put back hollow ellipsoid support, tho.

2021-02-01 22:39 UTC, Firigion commented on world-edit.sc
>  );
`feature` brush was not added to the new brush call formatting.

2021-02-01 22:39 UTC, Firigion commented on world-edit.sc
> +    call(global_brush_shapes:action,player~'pos',args,flags)
`shape` seems to never be called. Idk if the idea was to use it to call the shape commands, but this seems to have been dropped. If that was the case, I think it would be a good opportunity to implement something I was meaning to: have the `shape`s take in an extra argument being position, rather than always being centered around the player. That way, stuff like `shape cube <block> <size> <replacement> f <flag>'` would become `shape cube <pos> <block> <size> <replacement> f <flag>'`, which is arguably more useful.

2021-02-02 07:28 UTC, Ghoulboy78 commented on docs/Documentation.md
> +    perpendicular to `axis`, if given.
so It fits on my screen... I can undo if u want.

2021-02-02 07:28 UTC, Ghoulboy78 commented on world-edit.sc
> +            add_to_history('action_ellipsoid',player())
k.

2021-02-02 07:29 UTC, Ghoulboy78 commented on world-edit.sc
>  );
I didnt notice it there to begin with, but I'll add.

2021-02-02 07:30 UTC, Ghoulboy78 commented on world-edit.sc
> +    call(global_brush_shapes:action,player~'pos',args,flags)
umm, oh wait maybe I havent committed. But yeah, I do call shape () in the command.

2021-02-02 07:32 UTC, Ghoulboy78 commented
> Good work! You really need to be more careful when modifying existing code, tho. Especially if it was written by someone else. This is the third or fourth time you accidentally delete features that had been implemented by someone else.
> 
> Also, why you are overhauling brush, would you mind importing `pyramid` over form carpet's draw app/comand? That was a shape I was missing.

Soz abt that. I will re-haul some of the stuff once gnembon accepts gnembon/fabric-carpet#618, cos it will make the code so much cleaner.

2021-02-02 07:35 UTC, Ghoulboy78 commented on world-edit.sc
> +    call(global_brush_shapes:action,player~'pos',args,flags)
Also, isn't that basically a buffed up copy of draw command?

2021-02-02 15:44 UTC, Firigion commented on docs/Documentation.md
> +    perpendicular to `axis`, if given.
I'm not sure. I'm just curious why. On my screen it auto adjusts. Both on desktop and mobile. It's odd that it doesn't do it for you... But leave it like that, if it's easier for you, dw

2021-02-02 15:46 UTC, Firigion commented on world-edit.sc
> +    call(global_brush_shapes:action,player~'pos',args,flags)
Yes, but with all the added functionality of WS: flags, pallette support (one we add those), undo and so on. Also, yeah, it's probably not commited or pushed, because as of now, it's not called.

2021-02-04 21:14 UTC, Ghoulboy78 commented on world-edit.sc
> +            add_to_history('action_ellipsoid',player())
actually firi aimma add hollow support to those as well.

2021-02-04 21:14 UTC, Ghoulboy78 commented on world-edit.sc
> +            add_to_history('action_ellipsoid',player())
I have rly gr8 algorithm in mind to do it eficiently

2021-02-10 04:26 UTC, Firigion commented on world-edit.sc
> +            add_to_history('action_ellipsoid',player())
Hollow cube and cuboid are already added. Check out #52, I don't think it gets any more efficient than that. If you think it does, go ahead, but don't do extra work if it's not needed :P

2021-02-10 14:39 UTC, BisUmTo approved these changes

2021-02-10 14:43 UTC, BisUmTo commented
I didn't find the time to check every command combination...
I read that part on my mobile 9 days ago and I couldn't find any problem.
The new Brush addition system fits really well on my opinion...

2021-02-13 19:11 UTC, Firigion commented
Still missing hollow ellipsoid, tho. Just add back the old carver to make shapes hollow. If you have time, try also adding pyramind from [draw_beta.sc](https://github.com/gnembon/fabric-carpet/blob/master/src/main/resources/assets/carpet/scripts/draw_beta.sc), so we have all the features in. If not, don't worry, I plan to add pyramids with polygon bases later, but I don't wanna merge a PR thaat removes features from the app, even if it's as unused one as hollow ellipsoids.

The rest of the added commands are nice. Gootta make sure to implement the new `_flood_generic` in #51 and remove the new hollow shapes in #52 (from #45).

2021-03-19 12:29 UTC, merged