Adding Drain, corresponding brush and new flag
Ghoulboy78/World-edit-scarpet pull request #51
Opened 2021-02-05 14:26 UTC by Firigion

Drain will remove all liquid connected to the block the player is standing in. By default it does it with some medium range (I think 25?), but the user can specify another value. If there's a selection and the player is standing within it and doesn't specify a radius, then the drain is performed within the selection.

The drain brush is basically the same, but it begins draining in the block the user clicked. Since brush traces usually go through liquids to target the blocks behind them, I added a new flag `-l` that when applied to the creation of a brush, will make that brush target liquids as well as blocks. Drain brush defaults to that behavior, of course.

The implementation of drain is using the flood fill functionality in the background. Maybe there's a better way to do it, but that's what I could come up with.

2021-02-10 14:36 UTC, BisUmTo submitted a review, later dismissed

2021-02-16 01:21 UTC, Firigion commented
This PR now also contains #55, since it was merged into this one. Fo read that one if you want to comment on the functionality added there.

2021-03-21 08:52 UTC, Ghoulboy78 requested changes
Pretty good, just some things to worked out.

2021-03-21 08:52 UTC, Ghoulboy78 commented on world-edit.sc
> +        ),
2 entries for 'flood', which one do you wanna keep?

2021-03-21 08:52 UTC, Ghoulboy78 commented on world-edit.sc
> +_sq_distance(p1, p2) -> reduce(p1-p2, _a + _*_, 0);
Why not use _euclidean_sq function? It's already imported and used throughout the app...

2021-03-21 16:40 UTC, Firigion commented on world-edit.sc
> +_sq_distance(p1, p2) -> reduce(p1-p2, _a + _*_, 0);
Because it wasn't when I first wrote it, then I forgot to change it...

2021-03-21 16:40 UTC, Firigion commented on world-edit.sc
> +        ),
Woops, I thought I had deleted the old one!

2021-03-21 16:59 UTC, Ghoulboy78 approved these changes

2021-03-21 17:05 UTC, merged